$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignorePaths:
  - node_modules
  - bun.lockb
  - ./branch_out
  - .tsbuildinfo
  - "*.tsbuildinfo"
  - .gitignore
  - dist
  - storybook-static
  - .next
  - .astro
  - drizzle
  - "**/*.svg"
words:
  - acst
  - aest
  - akst
  - astro
  - astrojs
  - autodocs
  - autoplay
  - awst
  - Beamer
  - Binni
  - branchname
  - bunx
  - bvaughn
  - Byrom
  - callees
  - classname
  - clsx
  - cmdk
  - codespace
  - codespaces
  - Colm
  - commitlint
  - commitlintrc
  - compat
  - consts
  - crossorigin
  - datetime
  - degit
  - Duarte
  - Elsakaan
  - Embla
  - esbenp
  - Hesham
  - hookform
  - ianvs
  - ixahmedxi
  - jiti
  - lockb
  - lucide
  - Malyavko
  - minimise
  - Mintlify
  - monorepoing
  - neonctl
  - neondatabase
  - nextjs
  - nzst
  - optimisations
  - Ornella
  - packagejson
  - pacocoursey
  - pageview
  - peduarte
  - posthog
  - quickstart
  - Ratelimit
  - rechain
  - shadcn
  - sslmode
  - starterkit
  - starterkits
  - stylesheet
  - superjson
  - tada
  - tailwindcss
  - tanstack
  - thollander
  - todos
  - topbar
  - transpiles
  - trpc
  - tsbuildinfo
  - tsconfigs
  - tseslint
  - tsup
  - Tuite
  - turborepo
  - typecheck
  - typeof
  - typesafe
  - unkey
  - uploadthing
  - vaul
  - viewports
  - WITA
